# DO NOT PUSH THIS
api: "https://vincent-your-news-anchor.azurewebsites.net" # The endpoint where the database API is located
max_articles_per_source: 2 # The max number of articles to scrap from a given source
security_token: "YrsKqDa5k8fAfIMmIQ1eXZQ99fgTPFbVebDyQy5MXK5YDP4BGTHhUTjDRw5qDw7P"
